<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>9387e6d2-4f57-4ece-bd9d-094c6978a836</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_web_testing</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/main[1]/div[3]/footer[1]/div[1]/div[2]/div[1]/div[3]/div[2]/a[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.link[href='\/web-testing']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'link platform-link')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>link platform-link</value>
        <webElementGuid>64c85f00-3a52-4a1e-b170-75f1b0c888bd</webElementGuid>
    </webElementProperties>
</WebElementEntity>