<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0934c220-587d-447c-92ff-f43399ed440a</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_pricing</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/main[1]/div[3]/footer[1]/div[1]/div[2]/div[1]/div[2]/div[2]/a[5]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.link[href='\/pricing']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'link platform-link')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>link platform-link</value>
        <webElementGuid>c108778b-bc38-4254-8467-c2ff8a1277a1</webElementGuid>
    </webElementProperties>
</WebElementEntity>