<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>405222ca-dfb1-4179-b0f7-1d7567cae9a5</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_pricing</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/main[1]/div[3]/footer[1]/div[1]/div[2]/div[1]/div[2]/div[2]/a[5]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.link[href='\/pricing']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'link platform-link')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>link platform-link</value>
        <webElementGuid>bb7c7c74-b823-42b8-83fc-fcfdc92f5cf6</webElementGuid>
    </webElementProperties>
</WebElementEntity>