<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4f8cca73-bda9-4ad8-bdd3-91b176c4e8ad</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_business_outcomes</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/main[1]/div[3]/footer[1]/div[1]/div[2]/div[1]/div[1]/div[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.link[href='\/business-outcomes']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'link why-katalon-link')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>link why-katalon-link</value>
        <webElementGuid>dbd914d4-a647-4c66-a7f4-724b41e7c648</webElementGuid>
    </webElementProperties>
</WebElementEntity>